rs:
  mysql:
    host: localhost
    port: 3306
    username: root
    password: <MYSQL_PASSWORD>

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rs.mysql.host}:${rs.mysql.port}/${rs.mysql.db-name}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${rs.mysql.username}
    password: ${rs.mysql.password}
